import type { Doc } from "./docs";
import { site } from "@/lib/site";

export const operationsDocs: Doc[] = [
  {
    slug: "github-apps",
    title: "GitHub Apps",
    description: "Short-lived installation tokens, signed webhooks and deployment feedback.",
    group: "Core",
    source: "GITHUB_APP.md",
    blocks: [
      { kind: "h2", text: "Connect an installation" },
      { kind: "p", text: "An operator registers an App under Sources → GitHub Apps through GitHub's manifest flow, or enters an existing App manually, including GitHub Enterprise Server. Each installation becomes a source. Private clones use repository-scoped, read-only tokens that live in memory for at most an hour; the App credentials are encrypted at rest." },
      { kind: "h2", text: "Deploy and report back" },
      { kind: "list", items: [
        "Push and PR webhooks are signature-checked and deduplicated, then matched by repository ID so renames and transfers keep working.",
        "The Deploy Wizard links new services to their selected App repository. Existing services can migrate, finalize or revert from Settings → GitHub. Migration keeps the PAT and webhook until finalization.",
        "Opt in to commit statuses and a single updated preview comment per PR. Feedback failure never fails the deployment.",
        "Private App clones on remote nodes require agent v0.13.0 or newer over sealed transport and Git ≥ 2.31. The panel checks capabilities before minting a per-job token.",
      ] },
      { kind: "code", body: "ninedeploy github-app list\nninedeploy services github\n\n# SDK: client.githubApps and client.services.github" },
    ],
  },
  {
    slug: "terminals",
    title: "Terminals",
    description: "Real TTY shells with resize, session limits and metadata audits.",
    group: "Interfaces",
    source: "TERMINALS.md",
    blocks: [
      { kind: "h2", text: "Open a container or database shell" },
      { kind: "p", text: "Instance operators can open shells from service and database pages, the CLI or client.terminals in the SDK. Local and node-placed Docker services get a real TTY with resize. For Compose, open a managed container instead of the service target. Database client mode supports psql, mysql/mariadb, redis-cli and valkey-cli." },
      { kind: "code", body: "ninedeploy terminal service 12\nninedeploy terminal db 3\nninedeploy terminals list\nninedeploy terminals kill <session-id>" },
      { kind: "h2", text: "Host terminals and remote nodes" },
      { kind: "callout", tone: "warn", title: "Host shells are off by default", text: "An operator must enable host shells under Settings → Security using an interactive browser session and a password re-check (or a recent SSO sign-in). Every host-shell session requires the same check. NINEDEPLOY_HOST_TERMINAL=off forbids panel host shells; NINEDEPLOY_AGENT_HOST_TERMINAL=off forbids them on a node." },
      { kind: "p", text: "Node terminals require agent v0.15.0 or newer and sealed transport. Update the agent from the Servers bootstrap flow. Terminal frames use an encrypted, authenticated channel; older agents get an explicit upgrade refusal. Workspace admins and fine-grained API tokens cannot open terminals." },
      { kind: "h2", text: "History and privacy" },
      { kind: "p", text: "Short-lived single-use tickets, idle limits, maximum duration and user/panel caps govern sessions. History records the user, target, client IP, duration, byte counts and end reason, with start/end audits. Typed commands and terminal output are never stored. Operators can terminate active sessions." },
    ],
  },
  {
    slug: "traffic-analytics",
    title: "Traffic analytics",
    description: "Opt-in request, status and latency charts from Traefik.",
    group: "Core",
    source: "TRAEFIK_INGRESS.md",
    blocks: [
      { kind: "h2", text: "Enable and view analytics" },
      { kind: "p", text: "Traffic analytics is off by default. An operator enables it on the Traefik page; this recreates Traefik once to activate its access log. With analytics off, upgrading to 0.15 leaves proxy configuration unchanged. The Traefik page shows the instance summary, and each service Overview shows its own chart." },
      { kind: "h2", text: "What is retained" },
      { kind: "list", items: [
        "Request counts, status classes and latency grouped by domain and service.",
        "Access logs omit client IP, path, query and headers.",
        "Minute rollups are kept for 48 hours; hourly rollups for 30 days by default.",
        "Traffic summaries are available through the CLI, SDK and generated read-only MCP tools.",
      ] },
    ],
  },
  {
    slug: "database-access-import",
    title: "Database access & imports",
    description: "Publish selected databases and import dumps with a safety backup.",
    group: "Core",
    source: "DATABASES_BACKUPS.md",
    blocks: [
      { kind: "h2", text: "Public TCP access" },
      { kind: "p", text: "Public access is off until an operator configures it. PostgreSQL, MySQL, MariaDB, Redis, Valkey and MongoDB can use a dedicated Traefik TCP sidecar on one host port, leaving the main proxy unchanged. An IP allowlist is mandatory, with at most 100 ranges and no /0. Uploaded-certificate TLS termination is optional and unavailable for MySQL/MariaDB." },
      { kind: "callout", tone: "info", title: "Connection credentials", text: "The credentials response includes publicConnectionString. It uses the database's root credentials; create a limited database user for application or external access." },
      { kind: "h2", text: "Import an existing dump" },
      { kind: "list", items: [
        "Database admins can upload resumable 8 MiB chunks. Operators can select an object in a backup destination.",
        "Supported formats: PostgreSQL custom/plain SQL, MySQL/MariaDB SQL, MongoDB archive and Redis/Valkey RDB, optionally gzipped.",
        "A pre-import safety backup is created first, followed by a check that the panel can still authenticate to the database.",
        "Use the database page, databases public-access|import|imports in the CLI, or the SDK's importFile helper. MCP exposes state and history through read-only tools.",
      ] },
      { kind: "h2", text: "Backup policies and panel recovery" },
      { kind: "p", text: "Per-database policies choose a cron schedule, local retention, remote retention and destination. Without a policy the default is a daily backup with 7 kept. Panel self-backup separately protects SQLite, the master key, .env and Traefik config with a recovery passphrase and off-site retention; configure it under Settings → Panel backup." },
    ],
  },
  {
    slug: "secret-managers",
    title: "External secret managers",
    description: "Resolve Vault / OpenBao and AWS Secrets Manager at deploy time.",
    group: "Security",
    source: "SECRET_MANAGERS.md",
    blocks: [
      { kind: "h2", text: "Configure a provider" },
      { kind: "p", text: "Operators configure HashiCorp Vault / OpenBao KV v2 or AWS Secrets Manager under Settings → Integrations. Provider credentials are encrypted and covered by master-key rotation. Infisical and Doppler references continue to work." },
      { kind: "code", file: "env references", body: 'DATABASE_PASSWORD=${{vault:apps/api#password}}\nAPI_TOKEN=${{aws:production/api#token}}' },
      { kind: "h2", text: "Deployment behavior" },
      { kind: "list", items: [
        "Each distinct Vault path or AWS secret is fetched once per deploy, passed to the container and never stored as a resolved value.",
        "The provider's workspace allowlist controls which services may use references.",
        "PR previews withhold references and preview-only environment values refuse them.",
        "When a provider is absent or disabled, its reference stays literal and the deploy log warns using env key names. Configure the provider before relying on resolution.",
      ] },
    ],
  },
  {
    slug: "upgrade-guide",
    title: "Upgrading & rollback",
    description: "Upgrade commands, node capabilities and release-specific rollback notes.",
    group: "Start",
    source: "QUICKSTART.md",
    blocks: [
      { kind: "h2", text: "Upgrade through the installer" },
      { kind: "code", body: `${site.install}\n\n# Installer-managed Docker\n${site.installDocker}\n\n# Pin a release\n${site.install} -s -- --version v${site.version}\n\n# Track main\n${site.install} -s -- --channel main` },
      { kind: "p", text: "Bare-metal upgrades snapshot the database and master key, rebuild, migrate and gate readiness on /health. Installer-managed Docker installs keep an image pin, so a plain compose pull re-pulls the same release; re-run --docker to upgrade. The dashboard's self-update button is available on systemd bare-metal panels." },
      { kind: "h2", text: "Moving to 0.15" },
      { kind: "list", items: [
        "Migration 0071 adds terminal_sessions, traffic_rollups and access_grants. Existing rows are unchanged.",
        "Host shells and traffic analytics start off. Existing access behavior stays the same until a grant is configured.",
        "Update remote agents to v0.15.0 for node terminals. Private GitHub App clones need agent v0.13.0 or newer.",
        "For older installs, review the intervening release notes too: 0.14 recreates Traefik once, and the 0.11.2 security notes describe when Git source tokens need rotation.",
      ] },
      { kind: "h2", text: "Rollback" },
      { kind: "p", text: "Rollback to 0.14 is supported: the new tables are ignored and grant-only access is lost. If analytics was enabled, 0.14 recreates Traefik without the access log. Read docs/ROLLBACK.md in the repository for terminal-helper cleanup and the additional steps when rolling back across earlier releases." },
    ],
  },
];
